#!/bin/sh

#
# Connect-to script
#
# Version 0.001
# Written by Aleksey Philippov <alks.philippov@gmail.com>
#

# Config vars
myhosts='/home/alksf/.myhosts'
sshfsdirs='/home/alksf/mnt/sshfs/'

if [ $1 ] ; then
    case  $1 in
        '-l')
            cat $myhosts
            ;;     
        '-s')      
            grep --color=auto -i $2 $myhosts
            ;;   
        '-m')    
            host=$(grep -i $2 $myhosts | cut -f3 -d":")
            dirname=$(grep -i $2 $myhosts | cut -f1 -d":")
            sshfs $host:/ $sshfsdirs$dirname
            ;;    
        '-c')     
            host=$(grep -i $2 $myhosts | cut -f3 -d":")
            method=$(grep -i $2 $myhosts | cut -f2 -d":")
            $method $host
            ;;
    esac
else
    echo 'ussage: connect-to [КЛЮЧ]/[ХОСТ]'
    echo '-c - Connect to host'
    echo '-l - List hosts'
    echo '-m - Mount host by sshfs'
    echo '-s - Search host[-s]'
fi
