#!/bin/sh

#
# Connect-to script
#
# Version 0.003
# Written by Aleksey Philippov <alks.philippov@gmail.com>
#

# Config vars
myhosts='/home/alksf/.myhosts'
sshfsdirs='/home/alksf/mnt/sshfs/'
browser='/usr/bin/iceweasel'

if [ $1 ] ; then
    case  $1 in
        '-l')
            cat $myhosts
            ;;     
        '-s')      
            grep --color=auto -i $2 $myhosts
            ;;   
        '-m')    
            host=$(grep -i $2 $myhosts | cut -f3 -d";")
            dirname=$(grep -i $2 $myhosts | cut -f1 -d";")
            method=$(grep -i $2 $myhosts | cut -f2 -d";")
            if [ $method = "ssh" ]
            then sshfs $host:/ $sshfsdirs$dirname
            else echo 'Only SSH hosts supports this feature.'
            fi
            ;;    
        '-c')     
            host=$(grep -i $2 $myhosts | cut -f3 -d";")
            method=$(grep -i $2 $myhosts | cut -f2 -d";")
            if [ $method = "browser" ]
            then $browser $host
            else $method $host
            fi
            ;;
        '-k')
            host=$(grep -i $2 $myhosts | cut -f3 -d";")
            method=$(grep -i $2 $myhosts | cut -f2 -d";")
            if [ $method = "ssh" ]
            then ssh-copy-id $host
            else echo 'Only SSH hosts supports this feature.'
            fi
            ;;
        '-e')
            host=$(grep -i $2 $myhosts | cut -f3 -d";")
            method=$(grep -i $2 $myhosts | cut -f2 -d";")
            if [ $method = "ssh" ]
            then $method $host $3
            else echo 'Only SSH hosts supports this feature.'
            fi
            ;;
    esac
else
    echo 'ussage: connect-to [OPTION]/[HOST] [COMMAND]'
    echo '-c - Connect to host'
    echo '-l - List hosts'
    echo '-s - Search host[-s]'
    echo '-m - Mount host by sshfs (Only for ssh hosts)'
    echo '-e - Execute command. (Only for ssh hosts)'
    echo '-k - Use locally available keys to authorise logins on a remote machine'
fi


